MODEL:
  TYPE: vHeat
  NAME: vHeat_small
  DROP_PATH_RATE: 0.3
  VHEAT:
    EMBED_DIM: 96
    DEPTHS: [2, 2, 18, 2]
    LAYER_SCALE: 1.e-5
    POST_NORM: True
TRAIN:
  BASE_LR: 5.e-4
  WEIGHT_DECAY: 0.08
SAVE_FREQ: 10
DATA:
  IMG_SIZE: 224